import renderer from "react-test-renderer";
import Board from "../../src/components/Board";

test("renders Board", () => {
  const tree = renderer.create(<Board guesses={6} wordLength={5} />).toJSON();
  expect(tree).toMatchInlineSnapshot(`
<div
  aria-label="game-board"
  id="board"
>
  <span
    aria-label="game-row"
  >
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
  </span>
  <span
    aria-label="game-row"
  >
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
  </span>
  <span
    aria-label="game-row"
  >
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
  </span>
  <span
    aria-label="game-row"
  >
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
  </span>
  <span
    aria-label="game-row"
  >
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
  </span>
  <span
    aria-label="game-row"
  >
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
    <input
      aria-label="game-tile"
      maxLength={1}
      type="text"
    />
  </span>
</div>
`);
});
