import renderer from "react-test-renderer";
import Game from "../../src/components/Game";

test("renders Game", () => {
  const tree = renderer.create(<Game />).toJSON();
  expect(tree).toMatchInlineSnapshot(`
[
  <h1 />,
  <button
    onClick={[Function]}
  >
    Get a new word
  </button>,
  <div
    aria-label="game-board"
    id="board"
  >
    <span
      aria-label="game-row"
    >
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
    </span>
    <span
      aria-label="game-row"
    >
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
    </span>
    <span
      aria-label="game-row"
    >
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
    </span>
    <span
      aria-label="game-row"
    >
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
    </span>
    <span
      aria-label="game-row"
    >
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
    </span>
    <span
      aria-label="game-row"
    >
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
      <input
        aria-label="game-tile"
        maxLength={1}
        type="text"
      />
    </span>
  </div>,
]
`);
});
